
import Icons from '~/configs/menus/menuIcons.js'

export default function (appContext) {
  return {
    // Register Company Steppers
    steppers: [
      {
        icon: "fa-question-circle",
        title: "general",
        slotName: "step1",
      },
      {
        icon: "fa-lock",
        title: "company",
        slotName: "step2",
      },
      {
        icon: "fa-icons",
        title: "social_media",
        slotName: "step3",
      },
      {
        icon: "fa-comment-dots",
        title: "remarks",
        slotName: "step4",
      },
      {
        icon: "fa-thumbs-up",
        title: "done",
        slotName: "step5",
      },
    ],

    // breadcrumb
    breadcrumb: [

      {
        text: "content_management_system",
        disabled: true,
        to: "",
        icon: Icons.content_management_system,
      },
      {
        text: "design_request",
        disabled: true,
        to: "",
        icon: Icons.design_request,
      },
    ],

    //  tabItem
    tabItems: [
      {
        text: "all",
        icon: "fa-table",
        isSelected: 1,
        key: "all",
      },
      {
        text: "assigned",
        icon: "fa-user-check",
        isSelected: 0,
        key: "assigned",
      },
      {
        text: "not_assigned",
        icon: "fa-user-times",
        isSelected: 0,
        key: "not assigned",
      },
      {
        text: "waiting",
        icon: "fa-spinner",
        isSelected: 0,
        key: "waiting",
      },
      // {
      //   text: "in_storyboard",
      //   icon: "fa-hourglass-start",
      //   isSelected: 0,
      //   key: "in storyboard",
      // },
      // {
      //   text: "storyboard_review",
      //   icon: "fa-tasks",
      //   isSelected: 0,
      //   key: "storyboard review",
      // },
      // {
      //   text: "storyboard_rejected",
      //   icon: "fa-comment-slash",
      //   isSelected: 0,
      //   key: "storyboard rejected",
      // },
      {
        text: "in_design",
        icon: "fa-drafting-compass",
        isSelected: 0,
        key: "in design",
      },
      {
        text: "design_review",
        icon: "fa-tasks",
        isSelected: 0,
        key: "design review",
      },
      {
        text: "design_rejected",
        icon: "fa-tint-slash",
        isSelected: 0,
        key: "design rejected",
      },
      {
        text: "in_programming",
        icon: "fa-code",
        isSelected: 0,
        key: "in programming",
      },
      {
        text: "completed",
        icon: "fa-check",
        isSelected: 0,
        key: "completed",
      },
      {
        text: "cancelled",
        icon: "fa-times",
        isSelected: 0,
        key: "cancelled",
      },
      {
        text: "removed",
        icon: "fa-trash",
        isSelected: 0,
        key: "removed",
      },
    ],

    // table headers

    // table headers
    headers: [
      {
        text: "id",
        value: "code",
        select: false,
        id: 1,
        sortable: false,
        category_id: 1,
      },
      {
        text: "content_type",
        value: "content_type",
        select: false,
        id: 2,
        category_id: 2,
      },
      {
        text: "company",
        value: "company",
        select: false,
        id: 3,
        category_id: 2,
      },
      {
        text: "template",
        value: "template",
        select: false,
        id: 4,
        sortable: false,
        category_id: 1,
      },
      {
        text: "product_code",
        value: "product_code",
        select: false,
        id: 5,
        category_id: 2,
      },
      {
        text: "product_name",
        value: "product_name",
        select: false,
        id: 6,
        category_id: 2,
      },
      {
        text: "project_url",
        value: "project_url",
        select: false,
        sortable: false,
        id: 7,
        category_id: 2,
      },
      {
        text: "canva_video",
        value: "video",
        select: false,
        sortable: false,
        id: 8,
        category_id: 2,
      },
      {
        text: "priority",
        value: "priority",
        select: false,
        id: 9,
        sortable: false,
        category_id: 1,
      },
      {
        text: "percentage",
        value: "percentage",
        select: false,
        id: 10,
        sortable: false,
        category_id: 1,
      },
      // {
      //   text: "download_status",
      //   value: "download_status",
      //   select: false,
      //   id: 11,
      //   sortable: false,
      //   category_id: 1,
      // },
      {
        text: "request_type",
        value: "requestType",
        select: false,
        sortable: false,
        id: 12,
        category_id: 1,
      },
      {
        text: "total_time_spent",
        value: "total_time_spent",
        select: false,
        id: 13,
        sortable: false,
        category_id: 4,
      },
      {
        text: "assigned_user",
        value: "assignedUser",
        select: false,
        id: 14,
        sortable: false,
        category_id: 1,
      },
      {
        text: "status",
        value: "status",
        select: false,
        id: 15,
        sortable: false,
        category_id: 2,
      },
      {
        text: "order_type",
        value: "order_type",
        select: false,
        id: 16,
        sortable: false,
        category_id: 2,
      },
      // {
      //   text: "Sales Notes",
      //   value: "sales_note",
      //   select: false,
      //   id: 17,
      //   sortable: false,
      //   category_id: 2,
      // },
      // {
      //   text: "StoryBoard Note",
      //   value: "storyboard_note",
      //   select: false,
      //   id: 18,
      //   sortable: false,
      //   category_id: 2,
      // },
      // {
      //   text: "design_note",
      //   value: "design_note",
      //   select: false,
      //   sortable: false,
      //   id: 19,
      //   category_id: 2,
      // },
      {
        text: "landing_page_link",
        value: "landing_page_link",
        select: false,
        id: 20,
        sortable: false,
        category_id: 2,
      },
      // {
      //   text: "total_storyboard_rejected",
      //   value: "storyboard_reject_count",
      //   select: false,
      //   id: 21,
      //   sortable: false,
      //   category_id: 1,
      // },
      // {
      //   text: "total_design_rejected",
      //   value: "design_reject_count",
      //   select: false,
      //   id: 22,
      //   sortable: false,
      //   category_id: 1,
      // },
      // {
      //   text: "cancels",
      //   value: "cancels",
      //   select: false,
      //   id: 23,
      //   sortable: false,
      //   category_id: 1,
      // },
      // {
      //   text: "label",
      //   value: "label",
      //   select: false,
      //   id: 24,
      //   sortable: false,
      //   category_id: 1,
      // },
      {
        text: "created_by",
        value: "created_by",
        select: false,
        id: 25,
        sortable: false,
        category_id: 1,
      },

      // {
      //   text: "updated_by",
      //   value: "updated_by",
      //   select: false,
      //   id: 26,
      //   sortable: false,
      //   category_id: 4,
      // },

      {
        text: "created_at",
        value: "created_at",
        select: false,
        id: 27,
        sortable: false,
        category_id: 4,
      },
    ],
  };
}
