import Icons from "../menus/menuIcons";

export default [
  {
    text: "Personal File Management",
    // key: "personal_file_management",
    icon: Icons.personal_file_management,
    items: [
      {
        text: "My Drive",
        key: "my_drive",
        link: "/files/personal/drive",
        exact: true,
        scope: "mdvHM",
        icon: Icons.my_drive,
      },
      {
        text: "Recent Files",
        key: "recent_files",
        link: "/files/personal/recent",
        exact: true,
        scope: "rfvHM",
        icon: Icons.recent_files,
      },
      {
        text: "Favorites",
        key: "favorites",
        link: "/files/personal/favorites",
        exact: true,
        scope: "fvHM",
        icon: Icons.favorites,
      },
      {
        text: "Share",
        key: "share",
        subLink: "file-settings",
        scope: ["sfvHM", "mshvHM"],
        icon: Icons.share,

        items: [
          {
            text: "My Shares",
            key: "my_shares",
            link: "/files/personal/my_shares",
            exact: true,
            scope: "mshvHM",
            icon: Icons.my_shares,
          },
          {
            text: "Shared With Me",
            key: "shared_with_me",
            link: "/files/personal/shared",
            exact: true,
            scope: "sfvHM",
            icon: Icons.shared_with_me,
          },
        ],
      },
      {
        text: "Trash",
        key: "trash",
        link: "/files/personal/trash",
        exact: true,
        scope: "tfvHM",
        icon: Icons.trash,
      },
      {
        text: "Storage Requests",
        key: "storage_requests",
        link: "/files/personal/storage-requests",
        exact: true,
        scope: "strvHM",
        icon: Icons.storage_requests,
      },
      {
        text: "File Settings",
        key: "file_settings",
        link: "/files/personal/setting",
        exact: true,
        scope: "setvHM",
        icon: Icons.file_settings,
      },
      {
        text: "Settings",
        key: "settings",
        subLink: "file-settings",
        scope: ["sepvHM", "rnpvHM"],
        icon: Icons.settings,

        items: [
          {
            text: "Status Event List",
            key: "status_event_list",
            link: "/status_management/status_event/personal",
            exact: true,
            scope: "sepvHM",
            icon: Icons.status_event_list,
          },
          {
            text: "Reasons List",
            key: "reason_list",
            link: "/status_management/reasons/personal",
            exact: true,
            scope: "rnpvHM",
            icon: Icons.reason_list,
          },
        ],
      },
    ],
  },
  {
    text: "Application File Management",
    // key: "application_file_management",
    icon: Icons.application_file_management,
    items: [
      {
        text: "My Drive",
        key: "my_drive",
        link: "/files/application/drive",
        exact: true,
        scope: "mdvHM",
        icon: Icons.my_drive,
      },
    ],
  },
  {
    text: "Library",
    // key: "library",
    icon: Icons.library,
    items: [
      {
        text: "Library Files",
        key: "library_files",
        link: "/files/library/drive",
        exact: true,
        scope: "lfvHM",
        icon: Icons.library_files,
      },
      {
        text: "Quic Access",
        key: "quick_access",
        scope: ["rfvHM", "pfvHM"],
        icon: Icons.quick_access,
        items: [
          {
            text: "Recent Files",
            key: "recent_files",
            link: "/files/library/recent",
            exact: true,
            scope: "rfvHM",
            icon: Icons.recent_files,
          },
          {
            text: "Pinned Files",
            key: "pinned_files",
            link: "/files/library/pinned",
            exact: true,
            scope: "pfvHM",
            icon: Icons.pinned_files,
          },
        ],
      },
      {
        text: "Favorites",
        key: "favorites",
        link: "/files/library/favorites",
        exact: true,
        scope: "fvHM",
        icon: Icons.favorites,
      },
      {
        text: "Trash",
        key: "trash",
        link: "/files/library/trash",
        exact: true,
        scope: "tfvHM",
        icon: Icons.trash,
      },
    ],
  },
];
