import Icons from "../menus/menuIcons";

export default {
  text: "Master Management System",
  key: "master_management_system",
  icon: Icons.master_management_system,
  items: [
    {
      text: "Countries",
      key: "countries",
      link: "/masters/countries",
      exact: true,
      scope: "cnv",
      icon: Icons.countries,
    },
    {
      text: "Departments",
      key: "departments",
      link: "/masters/departments",
      exact: true,
      scope: "dpv",
      icon: Icons.departments,
    },
    {
      text: "Companies",
      key: "companies",
      link: "/masters/companies",
      exact: true,
      scope: "cmv",
      icon: Icons.companies,
    },
    {
      key: "business_locations",
      text: "Business Location",
      link: "/masters/businessLocations",
      exact: true,
      scope: "blv",
      icon: Icons.business_locations,
    },
    {
      text: "Language Setting",
      key: "language_setting",
      subLink: "language-settings",
      scope: ["lnv"],
      icon: Icons.language_setting,
      items: [
        {
          text: "Languages",
          key: "languages",
          link: "/languages",
          exact: true,
          scope: "lnv",
          icon: Icons.languages,
        },
        {
          text: "Translations",
          key: "translation",
          link: "/languages/translation",
          exact: true,
          scope: "lnv",
          icon: Icons.translation,
        },
      ],
    },
    {
      text: "Social Media List",
      key: "social_media",
      link: "/masters/social-media",
      exact: true,
      scope: "smv",
      icon: Icons.social_media,
    },
    {
      text: "Settings",
      key: "settings",
      subLink: "master-settings",
      scope: ["lmv", "rnmv", "semv"],
      icon: Icons.settings,
      items: [
        {
          text: "Status Event List",
          key: "status_event_list",
          link: "/status_management/status_event/master",
          exact: true,
          scope: "semv",
          icon: Icons.status_event_list,
        },
        {
          text: "Reasons List",
          key: "reason_list",
          link: "/status_management/reasons/master",
          exact: true,
          scope: "rnmv",
          icon: Icons.reason_list,
        },
        {
          text: "Labels",
          key: "labels",
          link: "/labels/master",
          exact: true,
          scope: "lmv",
          icon: Icons.labels,
        },
        {
          text: "Column Category",
          key: "column_category",
          link: "/system-setting/category-setting",
          exact: true,
          scope: "ccmv",
          icon: Icons.column_category,
        },
        {
          text: "Column Setting",
          key: "column_setting",
          link: "/system-setting/column-setting",
          exact: true,
          scope: "csmv",
          icon: Icons.column_setting,
        },
      ],
    },
    {
      text: "Activities List",
      key: "master_activity",
      link: "/logs/masters",
      exact: true,
      scope: "uav",
      icon: Icons.activity,
    },
  ],
};
