export default [
  {
    logo: "/icons/SYSTEM ICON/landing-page-logo-01.svg",
    color: "",
    text: "New Content Management System",
    // key: "new_content_management_system",
    items: [
      {
        icon: "mdi-note-edit",
        key: "design_request",
        text: "Design Request",
        link: "/new-landing-page/design-request/",
        exact: true,
        scope: "drvHM",
      },
      {
        icon: "mdi-star",
        key: "skills",
        text: "Skills",
        scope: ["rncvHM", "secvHM"],
        subLink: "new-landing-page",
        items: [
          {
            icon: "mdi-star",
            key: "skills_category",
            text: "Skills Category",
            link: "/new-landing-page/skills/categories",
            exact: true,
            scope: "secvHM",
          },
          {
            icon: "mdi-star",
            key: "skills_sub_category",
            text: "Skills SubCategory",
            link: "/new-landing-page/skills/subcategories",
            exact: true,
            scope: "secvHM",
          },
          {
            icon: "mdi-star",
            key: "skill",
            text: "skill",
            link: "/new-landing-page/skills",
            exact: true,
            scope: "drvHM",
          },
        ],
      },
      {
        icon: "mdi-folder-plus",
        key: "products",
        text: "products",
        scope: ["rncvHM", "secvHM"],
        subLink: "/new-landing-page/products",
        items: [
          {
            icon: "mdi-folder-plus",
            key: "product_category",
            text: "Products Category",
            link: "/new-landing-page/products/categories",
            exact: true,
            scope: "drvHM",
          },
          {
            icon: "mdi-folder-plus",
            key: "product_sub_category",
            text: "Products SubCategory",
            link: "/new-landing-page/products/subcategories",
            exact: true,
            scope: "drvHM",
          },
          {
            icon: "mdi-folder-plus",
            key: "product",
            text: "Product",
            link: "/new-landing-page/products",
            exact: true,
            scope: "drvHM",
          },
        ],
      },
      {
        icon: "mdi-folder-plus",
        key: "requirements",
        text: "requirements",
        scope: ["rncvHM", "secvHM"],
        subLink: "/new-landing-page/requirements",
        items: [
          {
            icon: "mdi-folder-plus",
            key: "requirement_category",
            text: "Requirements Category",
            link: "/new-landing-page/requirements/categories",
            exact: true,
            scope: "secvHM",
          },
          {
            icon: "mdi-folder-plus",
            key: "requirement_sub_category",
            text: "Requirements SubCategory",
            link: "/new-landing-page/requirements/subcategories",
            exact: true,
            scope: "secvHM",
          },
        ],
      },
      {
        icon: "mdi-folder-plus",
        key: "workers",
        text: "workers",
        scope: ["rncvHM", "secvHM"],
        subLink: "/new-landing-page/workers",
        items: [
          {
            icon: "mdi-folder-plus",
            key: "worker_category",
            text: "Workers Category",
            link: "/new-landing-page/workers/categories",
            exact: true,
            scope: "secvHM",
          },
          {
            icon: "mdi-folder-plus",
            key: "worker_sub_category",
            text: "Workers SubCategory",
            link: "/new-landing-page/workers/subcategories",
            exact: true,
            scope: "secvHM",
          },
        ],
      },
    ],
  },
];
