import Icons from "../menus/menuIcons";
export default {
  color: "",
  text: "Advertisement Management System",
  key: "advertisement_management_system",
  icon: Icons.advertisement_management_system,
  items: [
    {
      text: "advertisement",
      key: "advertisement",
      link: "/advertisement/",
      exact: true,
      scope: "advv",
      icon: Icons.advertisement_management_system,
    },
    {
      text: "manual-upload",
      key: "manual_upload",
      link: "/advertisement/manual-upload",
      exact: true,
      scope: "mpv",
      icon: Icons.advertisement_management_system,
    },
    {
      text: "IPA",
      key: "ipa",
      link: "/advertisement/ipa",
      exact: true,
      scope: "ipav",
      icon: Icons.ipa,
    },
    {
      text: "Landing Page",
      key: "landing Page",
      link: "/advertisement/landing_page",
      exact: true,
      scope: "ipav",
      icon: Icons.ipa,
    },

    {
      text: "Settings",
      key: "settings",
      subLink: "advertisement-settings",
      scope: ["lav"],
      icon: Icons.settings,
      items: [
        {
          text: "platforms",
          key: "platforms",
          link: "/advertisement/platforms",
          exact: true,
          scope: "advplatformsv",
          icon: Icons.platforms,
        },
        {
          text: "projects",
          key: "projects",
          link: "/advertisement/projects",
          exact: true,
          scope: "advprojectsv",
          icon: Icons.projects,
        },
        {
          text: "applications",
          key: "applications",
          link: "/advertisement/applications",
          exact: true,
          scope: "advappsv",
          icon: Icons.applications,
        },
        // {
        //   text: "account_pixels",
        //   key: "account_pixels",
        //   link: "/advertisement/account-pixels",
        //   exact: true,
        //   scope: "advappsv",
        //   icon: Icons.applications,
        // },
        {
          text: "Labels",
          key: "labels",
          link: "/labels/advertisement",
          exact: true,
          scope: "lav",
          icon: Icons.labels,
        },
        {
          text: "Status Event List",
          key: "status_event_list",
          link: "/status_management/status_event/advertisement",
          exact: true,
          scope: "seav",
          icon: Icons.status_event_list,
        },
        {
          text: "Reasons List",
          key: "reason_list",
          link: "/status_management/reasons/advertisement",
          exact: true,
          scope: "rnav",
          icon: Icons.reason_list,
        },
        // {
        //   text: "Currency",
        //   key: "currency",
        //   link: "/advertisement/currency",
        //   exact: true,
        //   scope: "rnav",
        //   icon: Icons.labels,
        // },
      ],
    },
  ],
};
