export default function (appContext) {
	return {
		imageTypes: ["png", "jpg", "jpeg", "gif", "svg", "ico", "webp"],
		videoTypes: ["mp4", "mkv", "ogg", "mov", "webm"],
		pdfTypes: ["pdf"],
		audioTypes: ["mp3", "wav"],
		wordTypes: ["doc", "docm", "docx", "dot", "dotx"],
		excelTypes: [
			"xlsx",
			"xlsm",
			"xltx",
			"xltm",
			"xls",
			"xlt",
			"xls",
			"xla",
			"xlw",
			"xlr",
		],
		accessTypes: [
			"adp",
			"adn",
			"accdb",
			"laccdb",
			"accdw",
			"accdc",
			"accda",
			"accdr",
			"accdt",
			"mdb",
			"mda",
			"mdw",
			"mdf",
			"mde",
			"accde",
			"mam",
			"mad",
			"maq",
			"mar",
			"mat",
			"maf",
		],
		powerpointTypes: [
			"pptx",
			"pptm",
			"ppt",
			"potx",
			"potm",
			"pot",
			"ppsx",
			"ppsm",
			"pps",
			"ppam",
			"ppa",
		],
		photoshopTypes: ["psd", "psdc", "psb"],
		illustratorTypes: ["ai", "eps", "ait", "svgz"],
		indesignTypes: ["indd", "indl", "indt", "indb", "inx", "idml"],
		premierTypes: ["prel", "prproj"],
		afterEffectTypes: ["aaf", "aep", "aet", "aepx"],
		compressedTypes: ["zip", "rar"],
		folder: ["folder"],
	};
}
