<?php

namespace App\Providers;

use Laravel\Passport\Passport;
use Illuminate\Support\Facades\Gate;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\File;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The policy mappings for the application.
     *
     * @var array
     */
    protected $policies = [
        // 'App\Models\Model' => 'App\Policies\ModelPolicy',
    ];

    /**
     * Register any authentication / authorization services.
     *
     * @return void
     */
    public function boot()
    {
        // $this->registerPolicies();
        // $systemsFile = json_decode(File::get(resource_path() . "/json/systems.json"));
        // $actionFile = json_decode(File::get(resource_path() . "/json/actions.json"));
        // $arr = [];
        // foreach ($systemsFile as $key => $system) {
        //     $system = (array)$system;
        //     foreach ((array)$system['sub_systems'] as $key => $sub_system) {
        //         $sub_system = (array)$sub_system;
        //         foreach ((array)$sub_system['actions'] as $key => $action) {
        //             $action = (array)$action;
        //             foreach ($actionFile as $key => $actionF) {
        //                 $actionF = (array)$actionF;
        //                 if (
        //                     $actionF['name']
        //                     == $action['name']
        //                 ) {
        //                     foreach ((array)$actionF['sub_actions']  as $key => $subAction) {
        //                         $subAction = (array)$subAction;
        //                         $str = strtolower(str_replace(' ', '', $sub_system['scope']) . '' . $subAction['name']);
        //                         $arr[$str] = "Can " . $subAction['name'] . " " . $sub_system['name'];
        //                     }
        //                 }
        //             }
        //         }
        //     }
        // }
        // dd($arr);

        Passport::tokensCan(
            [
                "ud" => "Can d Users",
                "uu" => "Can u Users",
                "uv" => "Can v Users",
                "uc" => "Can c Users",
                "ue" => "Can e Users",
                "td" => "Can d Teams",
                "tu" => "Can u Teams",
                "tv" => "Can v Teams",
                "tc" => "Can c Teams",
                "te" => "Can e Teams",
                "rd" => "Can d Roles",
                "ru" => "Can u Roles",
                "rv" => "Can v Roles",
                "rc" => "Can c Roles",
                "re" => "Can e Roles",
                "uad" => "Can d User Activity"        ,
                "uau" => "Can u User Activity"        ,
                "uav" => "Can v User Activity"        ,
                "uac" => "Can c User Activity"        ,
                "uae" => "Can e User Activity"        ,
                "lud" => "Can d Labels (user)"        ,
                "luu" => "Can u Labels (user)"        ,
                "luv" => "Can v Labels (user)"        ,
                "luc" => "Can c Labels (user)"        ,
                "lue" => "Can e Labels (user)"        ,
                "seud" => "Can d Status Events (user)",
                "seuu" => "Can u Status Events (user)",
                "seuv" => "Can v Status Events (user)",
                "seuc" => "Can c Status Events (user)",
                "seue" => "Can e Status Events (user)",
                "rnud" => "Can d Reasons (user)"      ,
                "rnuu" => "Can u Reasons (user)"      ,
                "rnuv" => "Can v Reasons (user)"      ,
                "rnuc" => "Can c Reasons (user)"      ,
                "rnue" => "Can e Reasons (user)"      ,
                "bld" => "Can d Business Locations"   ,
                "blu" => "Can u Business Locations"   ,
                "blv" => "Can v Business Locations"   ,
                "blc" => "Can c Business Locations"   ,
                "ble" => "Can e Business Locations"   ,
                "smd" => "Can d Social Media",
                "smu" => "Can u Social Media",
                "smv" => "Can v Social Media",
                "smc" => "Can c Social Media",
                "sme" => "Can e Social Media",
                "cnd" => "Can d Countries",
                "cnu" => "Can u Countries",
                "cnv" => "Can v Countries",
                "cnc" => "Can c Countries",
                "cne" => "Can e Countries",
                "cmd" => "Can d Companies",
                "cmu" => "Can u Companies",
                "cmv" => "Can v Companies",
                "cmc" => "Can c Companies",
                "cme" => "Can e Companies",
                "dpd" => "Can d Departments",
                "dpu" => "Can u Departments",
                "dpv" => "Can v Departments",
                "dpc" => "Can c Departments",
                "dpe" => "Can e Departments",
                "lnd" => "Can d Languages",
                "lnu" => "Can u Languages",
                "lnv" => "Can v Languages",
                "lnc" => "Can c Languages",
                "lne" => "Can e Languages",
                "lmd" => "Can d Labels (master)",
                "lmu" => "Can u Labels (master)",
                "lmv" => "Can v Labels (master)",
                "lmc" => "Can c Labels (master)",
                "lme" => "Can e Labels (master)",
                "ccmd" => "Can d Column Category",
                "ccmu" => "Can u Column Category",
                "ccmv" => "Can v Column Category",
                "ccmc" => "Can c Column Category",
                "ccme" => "Can e Column Category",
                "csmd" => "Can d Column Setting",
                "csmu" => "Can u Column Setting",
                "csmv" => "Can v Column Setting",
                "csmc" => "Can c Column Setting",
                "csme" => "Can e Column Setting",
                "semd" => "Can d Status Events (master)",
                "semu" => "Can u Status Events (master)",
                "semv" => "Can v Status Events (master)",
                "semc" => "Can c Status Events (master)",
                "seme" => "Can e Status Events (master)",
                "rnmd" => "Can d Reasons (master)",
                "rnmu" => "Can u Reasons (master)",
                "rnmv" => "Can v Reasons (master)",
                "rnmc" => "Can c Reasons (master)",
                "rnme" => "Can e Reasons (master)",
                "syd" => "Can d Systems",
                "syu" => "Can u Systems",
                "syv" => "Can v Systems",
                "syc" => "Can c Systems",
                "sye" => "Can e Systems",
                "ispd" => "Can d ISPP",
                "ispu" => "Can u ISPP",
                "ispv" => "Can v ISPP",
                "ispc" => "Can c ISPP",
                "ispe" => "Can e ISPP",
                "acd" => "Can d Actions",
                "acu" => "Can u Actions",
                "acv" => "Can v Actions",
                "acc" => "Can c Actions",
                "ace" => "Can e Actions",
                "ssod" => "Can d My Order (Single Sales)",
                "ssou" => "Can u My Order (Single Sales)",
                "ssov" => "Can v My Order (Single Sales)",
                "ssoc" => "Can c My Order (Single Sales)",
                "ssoe" => "Can e My Order (Single Sales)",
                "ssoisb" => "Can isb My Order (Single Sales)",
                "ssoisbr" => "Can isbr My Order (Single Sales)",
                "ssoid" => "Can id My Order (Single Sales)",
                "ssoidr" => "Can idr My Order (Single Sales)",
                "ssoip" => "Can ip My Order (Single Sales)",
                "sesd" => "Can d Status Events (single_sale)",
                "sesu" => "Can u Status Events (single_sale)",
                "sesv" => "Can v Status Events (single_sale)",
                "sesc" => "Can c Status Events (single_sale)",
                "sese" => "Can e Status Events (single_sale)",
                "rnsd" => "Can d Reasons (single_sales)",
                "rnsu" => "Can u Reasons (single_sales)",
                "rnsv" => "Can v Reasons (single_sales)",
                "rnsc" => "Can c Reasons (single_sales)",
                "rnse" => "Can e Reasons (single_sales)",
                "advd" => "Can d Advertisement",
                "advu" => "Can u Advertisement",
                "advv" => "Can v Advertisement",
                "advc" => "Can c Advertisement",
                "adve" => "Can e Advertisement",
                "advrfdate" => "Can rfdate Advertisement",
                "advrfcrm" => "Can rfcrm Advertisement",
                "advrfsnapchat" => "Can rfsnapchat Advertisement",
                "advrftiktok" => "Can rftiktok Advertisement",
                "mpd" => "Can d Manual Upload",
                "mpu" => "Can u Manual Upload",
                "mpv" => "Can v Manual Upload",
                "mpc" => "Can c Manual Upload",
                "mpe" => "Can e Manual Upload",
                "mprefresh" => "Can refresh Manual Upload",
                "ipad" => "Can d ipa",
                "ipau" => "Can u ipa",
                "ipav" => "Can v ipa",
                "ipac" => "Can c ipa",
                "ipae" => "Can e ipa",
                "advplatformsd" => "Can d Platforms",
                "advplatformsu" => "Can u Platforms",
                "advplatformsv" => "Can v Platforms",
                "advplatformsc" => "Can c Platforms",
                "advplatformse" => "Can e Platforms",
                "advprojectsd" => "Can d Projects",
                "advprojectsu" => "Can u Projects",
                "advprojectsv" => "Can v Projects",
                "advprojectsc" => "Can c Projects",
                "advprojectse" => "Can e Projects",
                "advappsd" => "Can d Applications",
                "advappsu" => "Can u Applications",
                "advappsv" => "Can v Applications",
                "advappsc" => "Can c Applications",
                "advappse" => "Can e Applications",
                "lad" => "Can d Labels (advertisement)",
                "lau" => "Can u Labels (advertisement)",
                "lav" => "Can v Labels (advertisement)",
                "lac" => "Can c Labels (advertisement)",
                "lae" => "Can e Labels (advertisement)",
                "sead" => "Can d Status Events (advertisement)",
                "seau" => "Can u Status Events (advertisement)",
                "seav" => "Can v Status Events (advertisement)",
                "seac" => "Can c Status Events (advertisement)",
                "seae" => "Can e Status Events (advertisement)",
                "rnad" => "Can d Reasons (advertisement)",
                "rnau" => "Can u Reasons (advertisement)",
                "rnav" => "Can v Reasons (advertisement)",
                "rnac" => "Can c Reasons (advertisement)",
                "rnae" => "Can e Reasons (advertisement)",
                "curd" => "Can d Currencies",
                "curu" => "Can u Currencies",
                "curv" => "Can v Currencies",
                "curc" => "Can c Currencies",
                "cure" => "Can e Currencies",
                "osd" => "Can d Online Store",
                "osu" => "Can u Online Store",
                "osv" => "Can v Online Store",
                "osc" => "Can c Online Store",
                "ose" => "Can e Online Store",
                "losd" => "Can d Labels (online_sales)",
                "losu" => "Can u Labels (online_sales)",
                "losv" => "Can v Labels (online_sales)",
                "losc" => "Can c Labels (online_sales)",
                "lose" => "Can e Labels (online_sales)",
                "seosd" => "Can d Status Events (online_sales)",
                "seosu" => "Can u Status Events (online_sales)",
                "seosv" => "Can v Status Events (online_sales)",
                "seosc" => "Can c Status Events (online_sales)",
                "seose" => "Can e Status Events (online_sales)",
                "rnosd" => "Can d Reasons (online_sales)",
                "rnosu" => "Can u Reasons (online_sales)",
                "rnosv" => "Can v Reasons (online_sales)",
                "rnosc" => "Can c Reasons (online_sales)",
                "rnose" => "Can e Reasons (online_sales)",
                "prd" => "Can d Products",
                "pru" => "Can u Products",
                "prv" => "Can v Products",
                "prc" => "Can c Products",
                "pre" => "Can e Products",
                "catd" => "Can d Categories",
                "catu" => "Can u Categories",
                "catv" => "Can v Categories",
                "catc" => "Can c Categories",
                "cate" => "Can e Categories",
                "attd" => "Can d Attributes",
                "attu" => "Can u Attributes",
                "attv" => "Can v Attributes",
                "attc" => "Can c Attributes",
                "atte" => "Can e Attributes",
                "brd" => "Can d Brands",
                "bru" => "Can u Brands",
                "brv" => "Can v Brands",
                "brc" => "Can c Brands",
                "bre" => "Can e Brands",
                "prsd" => "Can d ProductStudy",
                "prsu" => "Can u ProductStudy",
                "prsv" => "Can v ProductStudy",
                "prsc" => "Can c ProductStudy",
                "prse" => "Can e ProductStudy",
                "pod" => "Can d My Order (Products)",
                "pou" => "Can u My Order (Products)",
                "pov" => "Can v My Order (Products)",
                "poc" => "Can c My Order (Products)",
                "poe" => "Can e My Order (Products)",
                "poisb" => "Can isb My Order (Products)",
                "poisbr" => "Can isbr My Order (Products)",
                "poid" => "Can id My Order (Products)",
                "poidr" => "Can idr My Order (Products)",
                "poip" => "Can ip My Order (Products)",
                "seprd" => "Can d Status Events (Product)",
                "sepru" => "Can u Status Events (Product)",
                "seprv" => "Can v Status Events (Product)",
                "seprc" => "Can c Status Events (Product)",
                "sepre" => "Can e Status Events (Product)",
                "rnprd" => "Can d Reasons (Product)",
                "rnpru" => "Can u Reasons (Product)",
                "rnprv" => "Can v Reasons (Product)",
                "rnprc" => "Can c Reasons (Product)",
                "rnpre" => "Can e Reasons (Product)",
                "lprd" => "Can d Labels (product)",
                "lpru" => "Can u Labels (product)",
                "lprv" => "Can v Labels (product)",
                "lprc" => "Can c Labels (product)",
                "lpre" => "Can e Labels (product)",
                "ssuprd" => "Can d Sourcing Request",
                "ssupru" => "Can u Sourcing Request",
                "ssuprv" => "Can v Sourcing Request",
                "ssuprc" => "Can c Sourcing Request",
                "ssupre" => "Can e Sourcing Request",
                "prld" => "Can d Product List",
                "prlu" => "Can u Product List",
                "prlv" => "Can v Product List",
                "prlc" => "Can c Product List",
                "prle" => "Can e Product List",
                "qrrd" => "Can d Quantity Reservation Request",
                "qrru" => "Can u Quantity Reservation Request",
                "qrrv" => "Can v Quantity Reservation Request",
                "qrrc" => "Can c Quantity Reservation Request",
                "qrre" => "Can e Quantity Reservation Request",
                "sod" => "Can d My Order (Suppliers)",
                "sou" => "Can u My Order (Suppliers)",
                "sov" => "Can v My Order (Suppliers)",
                "soc" => "Can c My Order (Suppliers)",
                "soe" => "Can e My Order (Suppliers)",
                "soisb" => "Can isb My Order (Suppliers)",
                "soisbr" => "Can isbr My Order (Suppliers)",
                "soid" => "Can id My Order (Suppliers)",
                "soidr" => "Can idr My Order (Suppliers)",
                "soip" => "Can ip My Order (Suppliers)",
                "sesupd" => "Can d Status Events (Supplier)",
                "sesupu" => "Can u Status Events (Supplier)",
                "sesupv" => "Can v Status Events (Supplier)",
                "sesupc" => "Can c Status Events (Supplier)",
                "sesupe" => "Can e Status Events (Supplier)",
                "rnsupd" => "Can d Reasons (Suppliers)",
                "rnsupu" => "Can u Reasons (Suppliers)",
                "rnsupv" => "Can v Reasons (Suppliers)",
                "rnsupc" => "Can c Reasons (Suppliers)",
                "rnsupe" => "Can e Reasons (Suppliers)",
                "lsupd" => "Can d Labels (supplier)",
                "lsupu" => "Can u Labels (supplier)",
                "lsupv" => "Can v Labels (supplier)",
                "lsupc" => "Can c Labels (supplier)",
                "lsupe" => "Can e Labels (supplier)",
                "crm_ordersd" => "Can d CRM Orders",
                "crm_ordersu" => "Can u CRM Orders",
                "crm_ordersv" => "Can v CRM Orders",
                "crm_ordersc" => "Can c CRM Orders",
                "crm_orderse" => "Can e CRM Orders",
                "cld" => "Can d Content library",
                "clu" => "Can u Content library",
                "clv" => "Can v Content library",
                "clc" => "Can c Content library",
                "cle" => "Can e Content library",
                "lcld" => "Can d Labels (content_library)",
                "lclu" => "Can u Labels (content_library)",
                "lclv" => "Can v Labels (content_library)",
                "lclc" => "Can c Labels (content_library)",
                "lcle" => "Can e Labels (content_library)",
                "secld" => "Can d Status Events (content_library)",
                "seclu" => "Can u Status Events (content_library)",
                "seclv" => "Can v Status Events (content_library)",
                "seclc" => "Can c Status Events (content_library)",
                "secle" => "Can e Status Events (content_library)",
                "rncld" => "Can d Reasons (content_library)",
                "rnclu" => "Can u Reasons (content_library)",
                "rnclv" => "Can v Reasons (content_library)",
                "rnclc" => "Can c Reasons (content_library)",
                "rncle" => "Can e Reasons (content_library)",
              ]
        );
        Passport::routes();
    }
}
